param(
  [string]$InputMd = "content.md",
  [string]$OutJson = "content.json",
  [string]$OutJs = "content-data.js"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function New-Slug([string]$s) {
  if ([string]::IsNullOrWhiteSpace($s)) { return "item" }
  $t = $s.ToLowerInvariant()
  $t = $t -replace "[^a-z0-9]+", "_"
  $t = $t.Trim("_")
  if ([string]::IsNullOrWhiteSpace($t)) { return "item" }
  return $t
}

function Add-UniqueKey([hashtable]$seen, [string]$base) {
  if (-not $seen.ContainsKey($base)) { $seen[$base] = 1; return $base }
  $seen[$base] = $seen[$base] + 1
  return ("{0}_{1}" -f $base, $seen[$base])
}

if (-not (Test-Path -LiteralPath $InputMd)) {
  throw "Input file not found: $InputMd"
}

$lines = Get-Content -LiteralPath $InputMd

$sections = @()
$currentSection = $null
$currentCard = $null
$seenItemKeys = @{}

function Ensure-Section([string]$key, [string]$title) {
  $script:currentSection = [ordered]@{
    key = $key
    title = $title
    description = ""
    cards = @()
  }
  $script:sections += $script:currentSection
  $script:currentCard = $null
}

function Ensure-Card([string]$title) {
  if ($null -eq $script:currentSection) { return }
  $script:currentCard = [ordered]@{
    title = $title
    note = ""
    items = @()
  }
  $script:currentSection.cards += $script:currentCard
}

foreach ($raw in $lines) {
  $line = ($raw ?? "").Trim()
  if ($line -eq "") { continue }

  # Section headers (emoji numbers optional)
  if ($line -match "(?i)\bEXTERIOR\b") {
    Ensure-Section -key "exterior" -title "Exterior"
    continue
  }
  if ($line -match "(?i)\bINTERIOR\b") {
    Ensure-Section -key "interior" -title "Interior"
    continue
  }
  if ($line -match "(?i)\bMECHANICAL\b") {
    Ensure-Section -key "mechanical" -title "Mechanical"
    continue
  }

  # Group/card header
  if ($line.StartsWith("🔹")) {
    # Avoid breaking surrogate pairs (emoji) by using replace instead of Substring(1).
    $cardTitle = ($line -replace "^\s*🔹\s*", "").Trim()
    Ensure-Card -title $cardTitle
    continue
  }

  # Notes / hints
  if ($line.StartsWith("تمرکز:") -or $line.StartsWith("⚠️") -or $line.StartsWith("📌")) {
    if ($null -ne $script:currentCard -and ($line.StartsWith("⚠️") -or $line.StartsWith("📌"))) {
      if ([string]::IsNullOrWhiteSpace($script:currentCard.note)) { $script:currentCard.note = $line }
      else { $script:currentCard.note += " " + $line }
    } elseif ($null -ne $script:currentSection -and $line.StartsWith("تمرکز:")) {
      if ([string]::IsNullOrWhiteSpace($script:currentSection.description)) { $script:currentSection.description = $line }
      else { $script:currentSection.description += " " + $line }
    }
    continue
  }

  # Skip content authoring helpers
  if ($line -match "(?i)^\s*optional tags\s*$") { continue }

  if ($null -eq $script:currentCard) {
    # If items appear before any card, create a default one.
    Ensure-Card -title "Checklist"
  }

  # Parse "Name (Subnote)" if present.
  $label = $line
  $sub = ""
  if ($line -match "^(.*)\\(([^)]*)\\)\\s*$") {
    $label = $matches[1].Trim()
    $sub = $matches[2].Trim()
  }

  $base = New-Slug $label
  $key = Add-UniqueKey -seen $seenItemKeys -base $base

  $item = [ordered]@{
    key = $key
    label = $label
    sublabel = $sub
    photo = $true
  }

  # If it explicitly says "if applicable", it's usually still checkable but photo optional.
  if ($line -match "(?i)if applicable") { $item.photo = $false }

  $script:currentCard.items += $item
}

$content = [ordered]@{
  meta = [ordered]@{
    generatedAt = (Get-Date).ToString("s")
    source = $InputMd
  }
  sections = $sections
}

$json = $content | ConvertTo-Json -Depth 20
Set-Content -LiteralPath $OutJson -Value $json -Encoding UTF8

$js = @()
$js += "/* Generated by scripts/generate-dvi-content.ps1 from $InputMd. */"
$js += "window.DVI_CONTENT = $json;"
$js += "window.DVI_CONTENT_META = window.DVI_CONTENT && window.DVI_CONTENT.meta ? window.DVI_CONTENT.meta : null;"
Set-Content -LiteralPath $OutJs -Value ($js -join "`r`n") -Encoding UTF8

Write-Host "Wrote $OutJson and $OutJs"
